name: Pull Request
on: [pull_request]

jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Cache dependencies
        id: node_modules-cache
        uses: actions/cache@preview
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: |
          yarn install

      - name: Lint code
        run: |
          yarn lint
