name: Release
on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Ready?
        run: |
          published_version=`git describe --abbrev=0 --tags`
          echo "Published version: $published_version"
          current_version=`npx -c 'echo "v$npm_package_version"'`
          echo "Current version: $current_version"
          if [ "$published_version" = "$current_version" ]; then
            # Continue workflow 
            exit 1
          else
            # Stop workflow
            exit 0
          fi

      - name: Release
        if: success()
        run: |
          echo "Running"
