name: Release
on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Ready?
        id: check-version
        run: |
          published_version=`git describe --abbrev=0 --tags`
          echo "Published version: $published_version"
          current_version=`npx -c 'echo "v$npm_package_version"'`
          echo "Current version: $current_version"
          if [ "$published_version" = "$current_version" ]; then
            echo ::set-output name=new-version::'false'
          else
            echo ::set-output name=new-version::'true'
          fi

      - name: Release
        if: steps.check-version.outputs.new-version == 'true'
        run: |
          echo "Running"
