name: Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Release
        run: |
          echo "Run Release"
