name: Release Tag
on: [push]

jobs:
  check-version-change:
    name: Check Version Change
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: New Version?
        run: |
          published_version=`git describe --abbrev=0 --tags`
          current_version=`yarn get-version | awk '/package.json: v[0-9]+.[0-9]+.[0-9]+/ {print $2}'`
          if ["$published_version" != "$current_version"]; then
            echo ::set-output name=new-version::true
          fi

  publish:
    name: Publish
    needs: check-version-change
    runs-on: ubuntu-18.04
    if: steps.check-version-change.outputs.new-version = 'true'
    steps:
      - name: Publishing
        run: |
          echo "Running"
